title: "Arch Writes"
description: "Ideas and reflections on diverse themes — from Arch Linux to Homer, passing through Jazz."
theme: minima
url: "https://viniciuspaeta.github.io"
baseurl: ""   # user site => vazio
plugins:
  - jekyll-feed
  - jekyll-seo-tag
